"""Pure domain contracts for audiovisual planning."""

from video_generator.domain.models import (
    SHORTS_PORTRAIT,
    YOUTUBE_LANDSCAPE,
    ContractError,
    EditOperation,
    EditPlan,
    FileFingerprint,
    RenderManifest,
    TargetFormat,
    ToolRecord,
    VideoBrief,
    VideoRequest,
)
from video_generator.domain.planning import (
    DEFAULT_RHYTHM_POLICY,
    AssetRequirement,
    AssetRequirements,
    NarrativeBlock,
    NarrativeScript,
    PlanningError,
    RhythmPolicy,
    Scene,
    ScenePlan,
    Shot,
    ShotPlan,
    apply_overrides,
    plan_scenes,
    plan_shots,
    shot_plan_to_edit_plan,
)

__all__ = [
    "AssetRequirement",
    "AssetRequirements",
    "ContractError",
    "DEFAULT_RHYTHM_POLICY",
    "EditOperation",
    "EditPlan",
    "FileFingerprint",
    "NarrativeBlock",
    "NarrativeScript",
    "PlanningError",
    "RenderManifest",
    "RhythmPolicy",
    "SHORTS_PORTRAIT",
    "Scene",
    "ScenePlan",
    "Shot",
    "ShotPlan",
    "TargetFormat",
    "ToolRecord",
    "VideoBrief",
    "VideoRequest",
    "YOUTUBE_LANDSCAPE",
    "apply_overrides",
    "plan_scenes",
    "plan_shots",
    "shot_plan_to_edit_plan",
]
# NOTE: implementation lands contract-by-contract via TDD; planning.py defines
# placeholders for the not-yet-built names so this import stays resolvable.
